spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-142.railway.app:$6691/railway
    username: root
    password: hhalChnfQ0mcAN8ZXjkQ
    name: spring-blog

  sql:
    init:
      mode: never  # you won't do this in prod, I'm just doing this for demo purposes